// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQLYpq_PUMzC9bfZUMQloG2h2E-cIXxfU',
    appId: '1:1075918910108:web:9eb381a1b8fe4e355af359',
    messagingSenderId: '1075918910108',
    projectId: 'appdoctorgpt',
    authDomain: 'appdoctorgpt.firebaseapp.com',
    storageBucket: 'appdoctorgpt.appspot.com',
    measurementId: 'G-CQF3NHN3SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWh-qvOSUQOnANGuVcOByJ0JFlFcMJoio',
    appId: '1:1075918910108:android:e7b76c059d42af7b5af359',
    messagingSenderId: '1075918910108',
    projectId: 'appdoctorgpt',
    storageBucket: 'appdoctorgpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXFyH2_ded_RX-8fYQscQQduZWl1sacc',
    appId: '1:1075918910108:ios:e657929bdd05d4885af359',
    messagingSenderId: '1075918910108',
    projectId: 'appdoctorgpt',
    storageBucket: 'appdoctorgpt.appspot.com',
    iosBundleId: 'com.example.doctorgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYXFyH2_ded_RX-8fYQscQQduZWl1sacc',
    appId: '1:1075918910108:ios:34255c34635982ec5af359',
    messagingSenderId: '1075918910108',
    projectId: 'appdoctorgpt',
    storageBucket: 'appdoctorgpt.appspot.com',
    iosBundleId: 'com.example.doctorgpt.RunnerTests',
  );
}
